# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respondant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('additional_comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_good', models.BooleanField()),
                ('proposal', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('respondant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Respondant')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_per_user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('annotation', models.TextField()),
                ('uri', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Term'),
        ),
    ]
