# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_respondant_identifier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('term', 'respondant')]),
        ),
    ]
