# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20170731_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='is_good',
            field=models.NullBooleanField(),
        ),
    ]
